language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tools
    - build-tools-27.0.2
    - build-tools-26.0.2
    - android-27
    - android-26
    - extra-android-m2repository
    - extra-google-google_play_services
    - extra-google-m2repository
    - sys-img-armeabi-v7a-android-26

before_script:
  - sdkmanager "system-images;android-26;google_apis;armeabi-v7a"
  # Create and start emulator
  - echo no | android create avd --force -n test -k "system-images;android-26;google_apis;armeabi-v7a"
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script: ./gradlew connectedAndroidTest
