language: java
os: linux
jdk: oraclejdk8
sudo: false
    
before_install:
  - source ./scripts/env.android.sh

before_script:
  # Create and start emulator
  - "$ANDROID_HOME"/tools/bin/sdkmanager "platform-tools" "system-images;android-26;default;armeabi-v7a" "android-26" "tools" "build-tools-27.0.2"
  - echo no | "$ANDROID_HOME"/tools/bin/avdmanager create avd --force -n test -t android-26 --abi armeabi-v7a --device "Nexus 5X" -k "system-images;android-26;default;armeabi-v7a"
  - "$ANDROID_HOME"/tools/bin/emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew clean installDebug
  - ./gradlew check
  - ./gradlew testDebugUnitTest
  - ./gradlew connectedDebugAndroidTest
