name: Android CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      ANDROID_SDK_TOOLS:    "4333796"
      ANDROID_CMAKE:        "3.10.2.4988404"
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install Android sdkmanager
      run: |
        wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-${ANDROID_SDK_TOOLS}.zip
        sudo unzip -d $ANDROID_HOME android-sdk.zip > /dev/null
    - name: Install required Android tools
      run: |
        echo "y" | sudo $ANDROID_HOME/tools/bin/sdkmanager "ndk;${ANDROID_NDK}" > /dev/null
    - name: Build with Gradle
      run: |
        export PATH="$ANDROID_HOME/cmake/${ANDROID_CMAKE}/bin:$PATH"
        ./gradlew build
    - name: run emulator
      run: |
        # Android SDK
        export PATH=$PATH:$ANDROID_HOME/emulator
        export ANDROID_HOME=/Users/markhan/Library/Android/sdk
        export PATH=$PATH:$ANDROID_HOME/platform-tools/
        export PATH=$PATH:$ANDROID_HOME/tools/bin/
        export PATH=$PATH:$ANDROID_HOME/tools/
        sdkmanager --install "system-images;android-27;google_apis;x86"
        echo "no" | avdmanager --verbose create avd --force --name "pixel_8.1" --device "pixel" --package "system-images;android-27;google_apis;x86" --tag "google_apis" --abi "x86"
    - name: run UI test
      run: ./gradlew connectedAndroidTest
